context.modules = [
    {
        name = libpipewire-module-roc-source
        args = {
            local.ip          = "0.0.0.0"
            local.source.port = 10001
            local.repair.port = 10002
            source.name       = "Roc Source"
            source.props = {
                node.name       = "roc-source"
                node.autoconnect = false
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Phone Mic (ROC)"
            capture.props = {
                node.name        = "capture.ROC_Input"
                target.object    = "roc-source"
                node.passive     = true
            }
            playback.props = {
                node.name        = "phone_mic_roc"
                media.class      = "Audio/Source"
                audio.position   = [ FL FR ]
            }
        }
    }
]
