# --- Playlist Management ---
F11         cycle-values loop-playlist yes no ; show-text "Loop: ${loop-playlist}"

# --- Video Control ---
Alt+r       cycle-values video-rotate 90 180 270 0 ; show-text "Rotation: ${video-rotate}°"
F9          cycle-values video-rotate 90 180 270 0 ; show-text "Rotation: ${video-rotate}°"
Ctrl+s      write-watch-later-config ; show-text "Watch Later Config Saved"
