#!/bin/sh

#
# WM Independent hotkeys
#

# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd

# Terminal emulator / tmux
super + {Return, shift + Return}
	{st, st -n tmux -e tmux}

# Dmenu
super + d
	{dmenu_run -p 'Select a program:'}

# Browser
super + shift + b
	firefox # tabbed -c surf -e

# File browser
super + shift + p
	st -n nnn -e nnn

# Lemonbar
super + shift + r
	pkill -x panel | pkill -x lemonbar | pkill polybar | polybar top &

# Script launcher
super + {shift + s, ctrl + s}
	{dmenulaunch, dmenuout}

#
# Special hotkeys
#

# Screenshots
Print
	scrot $HOME/Pictures/Screenshot-$(date +%F_%T).png -e "xclip -selection c -t image/png < $f"

super + Print
	scrot -s /tmp/Screenshot-$(date +%F_%T).png -e "xclip -selection c -t image/png < $f"

# Multimedia keys
XF86AudioRaiseVolume
	amixer sset Master 5%+

XF86AudioLowerVolume
	amixer sset Master 5%-

XF86AudioMute
	amixer sset Master toggle

#
# BSPWM Hotkeys
#

# Quit/Restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# Close and kill
super + {_,shift + }q
	bspc node -{c,k}

# Alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# Send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# Swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# State/Flags
#

# Set the window state
super + {t,p,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}
	
# Set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# Focus/Swap
#

# Focus the window in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# Focus the next/previous node in the current desktop
super + {_,shift + }Tab
	bspc node -f {next,prev}.local

# Focus the last node/desktop
super + {c, shift + c}
	bspc {node,desktop} -f last

# Focus or send to the given desktop
super + {_,shift + }{ampersand,eacute,quotedbl,apostrophe,parenleft,minus,egrave,underscore,ccedilla,agrave}
	bspc {desktop -f,node -d} '^{1-9}'
	
# Jump to another workspace
super + {ampersand,eacute,quotedbl,apostrophe,parenleft,minus,egrave,underscore,ccedilla,agrave}
	bspc desktop --focus^{1-9}

#
# Preselect
#

# Split Window
super + {h,v}
	bspc node -p {east,south}
	
# Preselect the split ratio
super + ctrl + {ampersand,eacute,quotedbl,apostrophe,parenleft,section,egrave,exclam,ccedilla,agrave}
	bspc node -o 0.{1-9}

# Cancel split
super + Escape
	bspc node -p cancel

#
# Move/Resize
#

# Expand windows
super + ctrl + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# Shrink windows
super + alt + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# Move floating windows
super + shift + {Left,Down,Up,Right}
	bspc node -v {-50 0,0 50,0 -50,50 0}

#
# Misc
#

# Adjust window gap on the fly
super + {KP_Add,KP_Subtract}
    bspc config window_gap $((\bspc config window_gap` {-,+} 20))`

# Hide window
super + h
	bspc node -g hidden

# Unhide window
super + shift + h
	bspc node {,$(bspc query -N -n .hidden | tail -n1)} -g hidden=off
