general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false
    ignore_wayland_inhibit = false
}

# 1. Dim screens after 3 minutes (180s)
listener {
    timeout = 180
    on-timeout = ~/.config/hypr/scripts/brightness-dim.sh
    on-resume = ~/.config/hypr/scripts/brightness-resume.sh
}

# 2. Lock Session after 5 minutes (300s)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off monitors after 10 minutes (600s)
listener {
    timeout = 600
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# 4. Deep Sleep / Suspend after 30 minutes (1800s)
#listener {
#    timeout = 1800
    # ignore_inhibit = true
#    on-timeout = loginctl suspend
#}
