general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 1.8, linear
}

background {
    monitor =
    path = /tmp/wall.jpg

    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.75
    vignette = 0.1
    vignette_thickness = 0.5

    color = rgb(23, 23, 23)
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0

    dots_size = 0.25
    dots_spacing = 0.35
    dots_center = true

    # Clean borderless translucent window look
    inner_color = rgba(40, 40, 40, 0.45)
    font_color = rgb(235, 219, 178)

    fade_on_empty = true
    fade_timeout = 1000

    placeholder_text = <span foreground="##ebdbb288"><i>Type Password...</i></span>
    hide_input = false
    fail_color = rgb(204, 36, 29)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 200

    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(235, 219, 178)
    font_size = 80
    font_family = Monospace Bold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %B %d")"
    color = rgba(235, 219, 178, 0.65)
    font_size = 16
    font_family = Monospace
    position = 0, 20
    halign = center
    valign = center
}
