#!/bin/sh
# Colorize commands when possible.
alias \
    ls="ls -shA --color=auto" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    dfg="df -BG" \
    dfm="df -BM" \
    ip="ip --color=auto" \

# Some more ls aliases.
alias \
    ll="ls -l --color=auto" \
    la="ls -A --color=auto" \
    llt="ls -latrG"

# xbps and pkg aliases.
alias \
    xbs="sudo xbps-install" \
    xbr="sudo xbps-remove -Rv" \
    xbq="xbps-query -Rs"

# apt aliases.
alias \
    apti="sudo apt-get install --no-install-recommends" \
    aptr="sudo apt-get --purge autoremove"

# zypper aliases.
alias \
    zyi="sudo zypper install --no-recommends" \
    zyr="sudo zypper remove --clean-deps --no-confirm"

# flatpak aliases.
alias \
    flinst="flatpak install" \
    flrem="flatpak uninstall --delete-data" \
    flclean="flatpak uninstall --unused --delete-data -y && flatpak repair"

# rsync aliases
alias \
    rsync="rsync -avh --progress" \
    rsync-ssh="rsync -avzh --progress -e ssh" \
    rsync-net="rsync -avzh --progress"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    clear="tput clear" \
    reset="tput reset"

# Network aliases
alias \
    gcl='git clone --depth 1' \
    nfs-mount="sudo mount -t nfs -o soft,timeo=50,retrans=2,intr,noac" \
    ssh-mount="sshfs -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,sshfs_sync"

# Utilities aliases
alias \
    pyserv="python3 -m http.server" \
    cleanup-history="tac \$HOME/.bash_history | awk '!seen[\$0]++' | tac | sed 's/[[:space:]]\+$//' > /tmp/.bash_history_tmp && mv -f /tmp/.bash_history_tmp \$HOME/.bash_history > /dev/null 2>&1" \
    cleanup-gamescope='pkill -9 -f "wine|wineserver|winedevice.exe|explorer.exe|gamescope-wl"' \

# Config aliases
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
