#!/bin/sh

# sxhkd
sxhkd -c $HOME/.config/bspwm/sxhkdrc -m 1 &

# Avoid doubling ruls
bspc rule -r "*"

# Workspace setup
bspc monitor -d I II III

# Workspaces
bspc rule -a 'chromium' desktop='^1'
bspc rule -a 'mpv' desktop='^3' center=on state=pseudo_tiled
bspc rule -a 'nnn' center=on state=pseudo_tiled

# General
bspc config split_ratio             0.52
bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

# Border & gaps
BW=2
bspc config border_width $BW
bspc config window_gap -2
bspc config top_padding 22
for side in right bottom left ; do
    bspc config ${side}_padding $BW
done

# Colors
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"
