#!/bin/sh
# Avoid doubling ruls
bspc rule -r "*"

# Workspace setup
bspc monitor -d I II III

# Lemonbar
pkill lemonbar | pkill bar | pkill sleep | pkill xtitle
#bar &

## Wallpaper setting
pkill xwinwrap | pkill xwallpaper | pkill sxiv

# Image
xwallpaper --zoom ~/Images/Walls/1.jpg &

# Animated background
#xwinwrap -ov -ni -fs -- mpv -vo x11 -wid WID --keepaspect=no --pause=no --loop ~/Images/Walls/1.gif &
#xwinwrap -ov -ni -fs -- sxiv -a -e WID -f -b -g 1366x768  ~/Images/Walls/1.gif &

# Compositor
pkill compton
compton -b &

# Default prefered settings
amixer -q set Master 100% &
xbacklight -set 60 &

# Workspaces settings
bspc rule -a 'Firefox' desktop='^1'
bspc rule -a 'mpv' desktop='^3' center=on state=pseudo_tiled
bspc rule -a 'nnn' center=on state=pseudo_tiled
bspc rule -a 'scratchpad' sticky=on center=on state=floating

# Split ratio and gapless monocle
bspc config split_ratio             0.52
bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true


## Nord theme
# Border gaps settings
bspc config border_width         2
bspc config window_gap           6
bspc config top_padding          18
bspc config bottom_padding       18
bspc config left_padding         18
bspc config right_padding        18

# Colors settings
bspc config focused_border_color    "#88C0D0"
bspc config normal_border_color     "#3B4252"
bspc config active_border_color     "#3B4252"
bspc config urgent_border_color     "#EBCB8B"
