#!/bin/sh

# Make the mouse visible
xsetroot -cursor_name left_ptr

# Avoid doubling ruls
bspc rule -r "*"

# Workspace setup
bspc monitor -d I II III

# Wallpapers
pkill -x xwinwrap | pkill -x hsetroot | pkill -x sxiv
	# Static background
	hsetroot -cover $HOME/Pictures/wall.webp
	#hsetroot -solid "#000000"

	# Animated background
	#xwinwrap -ov -ni -fs -- sxiv -a -e WID -f -b -g 1366x768 ~/Pictures/ani.webp &

# Picom (-CGb disable all effects)
pkill -x picom
picom -b &

# Defaults
amixer -q set Master 100% &
xbacklight -set 60 &

# Lemonbar
pkill -x panel
$HOME/.local/bin/lemonbar/cpanel | lemonbar -g x20 -f "-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1" -o -1 -f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" -B "#002b36" -F "#657b83" &

# Workspaces
bspc rule -a 'Firefox' desktop='^1'
bspc rule -a 'mpv' desktop='^3' center=on state=pseudo_tiled
bspc rule -a 'nnn' center=on state=pseudo_tiled

# General
bspc config split_ratio             0.52
bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

# Border & gaps
BW=2
bspc config border_width $BW
bspc config window_gap -2
bspc config top_padding 22
for side in right bottom left ; do
    bspc config ${side}_padding $BW
done

# Colors
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"
