# General Configuration
# output=                   # Blank auto-detects active/focused monitor on Wayland
min-width=200
max-width=420
max-height=300
stacking-order=bottom-up
anchor=bottom-right
edge-margin-vertical=12
edge-margin-horizontal=12
notification-margin=8
max-timeout=15
default-timeout=8
idle-timeout=0

# Appearance Settings
border-radius=8
layer=top
border-size=2
padding-vertical=10
padding-horizontal=12
icon-theme=breeze
max-icon-size=40

# Font Settings
title-font=sans-serif:size=11:weight=bold
title-format=<i>%a</i>
summary-font=sans-serif:size=11:weight=bold
summary-color=ebdbb2ff
summary-format=<b>%s</b>
body-font=sans-serif:size=10:weight=regular
body-color=ebdbb2ff
body-format=%b

progress-bar-height=5

# Notification Helpers
selection-helper=fuzzel
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Colors settings
# Start flavours
background=282828bf
border-color=b8bb26ff
title-color=b8bb26ff
progress-bar-color=b8bb26ff

[low]
background=282828bf
border-color=83a598ff
title-color=83a598ff
summary-color=d5c4a1ff
body-color=d5c4a1ff
default-timeout=4

# [normal]

[critical]
background=282828ef
border-color=fb4934ff
title-color=fb4934ff
summary-color=fabd2fff
body-color=ebdbb2ff
progress-bar-color=fb4934ff
default-timeout=0
# End flavours
