#!/bin/sh

sxhkd -c $HOME/.config/berry/sxhkdrc -m 1 &

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 3
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         6c71c4
berryc unfocus_color       073642
berryc inner_focus_color   7D97B8
berryc inner_unfocus_color 073642 
berryc text_focus_color    9BB3DC 
berryc text_unfocus_color  A6BBD9

# Other options
berryc pointer_focus "true"
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font "kakwafont-12"
